"""add BRD domain modules

Revision ID: 15f256465248
Revises: 72f88117e00d
Create Date: 2026-07-14 07:51:19.691090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f256465248'
down_revision: Union[str, Sequence[str], None] = '72f88117e00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('firm', sa.String(length=200), nullable=False),
    sa.Column('discipline', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultants_is_archived'), 'consultants', ['is_archived'], unique=False)
    op.create_index(op.f('ix_consultants_name'), 'consultants', ['name'], unique=False)
    op.create_index(op.f('ix_consultants_status'), 'consultants', ['status'], unique=False)
    op.create_index(op.f('ix_consultants_tenant_id'), 'consultants', ['tenant_id'], unique=False)
    op.create_table('cost_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_codes_code'), 'cost_codes', ['code'], unique=True)
    op.create_index(op.f('ix_cost_codes_is_archived'), 'cost_codes', ['is_archived'], unique=False)
    op.create_index(op.f('ix_cost_codes_tenant_id'), 'cost_codes', ['tenant_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registration_no', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_is_archived'), 'vendors', ['is_archived'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_index(op.f('ix_vendors_status'), 'vendors', ['status'], unique=False)
    op.create_index(op.f('ix_vendors_tenant_id'), 'vendors', ['tenant_id'], unique=False)
    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('defect_no', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_is_archived'), 'defects', ['is_archived'], unique=False)
    op.create_index(op.f('ix_defects_severity'), 'defects', ['severity'], unique=False)
    op.create_index(op.f('ix_defects_status'), 'defects', ['status'], unique=False)
    op.create_index(op.f('ix_defects_tenant_id'), 'defects', ['tenant_id'], unique=False)
    op.create_table('e_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('invoice_no', sa.String(length=60), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_e_invoices_invoice_no'), 'e_invoices', ['invoice_no'], unique=False)
    op.create_index(op.f('ix_e_invoices_is_archived'), 'e_invoices', ['is_archived'], unique=False)
    op.create_index(op.f('ix_e_invoices_status'), 'e_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_e_invoices_tenant_id'), 'e_invoices', ['tenant_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('receipt_no', sa.String(length=60), nullable=False),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('quantity_received', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('condition', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_is_archived'), 'goods_receipts', ['is_archived'], unique=False)
    op.create_index(op.f('ix_goods_receipts_status'), 'goods_receipts', ['status'], unique=False)
    op.create_index(op.f('ix_goods_receipts_tenant_id'), 'goods_receipts', ['tenant_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('inspection_no', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('inspector', sa.String(length=200), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_is_archived'), 'inspections', ['is_archived'], unique=False)
    op.create_index(op.f('ix_inspections_result'), 'inspections', ['result'], unique=False)
    op.create_index(op.f('ix_inspections_tenant_id'), 'inspections', ['tenant_id'], unique=False)
    op.create_table('progress_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('claim_no', sa.String(length=60), nullable=False),
    sa.Column('period', sa.String(length=30), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('certified_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_claims_is_archived'), 'progress_claims', ['is_archived'], unique=False)
    op.create_index(op.f('ix_progress_claims_status'), 'progress_claims', ['status'], unique=False)
    op.create_index(op.f('ix_progress_claims_tenant_id'), 'progress_claims', ['tenant_id'], unique=False)
    op.create_table('purchase_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('request_no', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requests_is_archived'), 'purchase_requests', ['is_archived'], unique=False)
    op.create_index(op.f('ix_purchase_requests_status'), 'purchase_requests', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_requests_tenant_id'), 'purchase_requests', ['tenant_id'], unique=False)
    op.create_table('site_diaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('diary_date', sa.DateTime(), nullable=True),
    sa.Column('weather', sa.String(length=100), nullable=False),
    sa.Column('manpower', sa.Integer(), nullable=False),
    sa.Column('work_summary', sa.Text(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=False),
    sa.Column('prepared_by', sa.String(length=200), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_diaries_diary_date'), 'site_diaries', ['diary_date'], unique=False)
    op.create_index(op.f('ix_site_diaries_is_archived'), 'site_diaries', ['is_archived'], unique=False)
    op.create_index(op.f('ix_site_diaries_tenant_id'), 'site_diaries', ['tenant_id'], unique=False)
    op.create_table('submittals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('submittal_no', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_by', sa.String(length=200), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submittals_is_archived'), 'submittals', ['is_archived'], unique=False)
    op.create_index(op.f('ix_submittals_status'), 'submittals', ['status'], unique=False)
    op.create_index(op.f('ix_submittals_tenant_id'), 'submittals', ['tenant_id'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tender_type', sa.String(length=30), nullable=False),
    sa.Column('submission_deadline', sa.DateTime(), nullable=True),
    sa.Column('awarded_vendor_id', sa.Integer(), nullable=True),
    sa.Column('awarded_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['awarded_vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_is_archived'), 'tenders', ['is_archived'], unique=False)
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_index(op.f('ix_tenders_tenant_id'), 'tenders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenders_title'), 'tenders', ['title'], unique=False)
    op.create_table('boq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=True),
    sa.Column('item_no', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boq_items_is_archived'), 'boq_items', ['is_archived'], unique=False)
    op.create_index(op.f('ix_boq_items_tenant_id'), 'boq_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_boq_items_tender_id'), 'boq_items', ['tender_id'], unique=False)
    op.create_table('payment_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('certificate_no', sa.String(length=60), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('retention_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['progress_claims.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_certificates_is_archived'), 'payment_certificates', ['is_archived'], unique=False)
    op.create_index(op.f('ix_payment_certificates_status'), 'payment_certificates', ['status'], unique=False)
    op.create_index(op.f('ix_payment_certificates_tenant_id'), 'payment_certificates', ['tenant_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('purchase_request_id', sa.Integer(), nullable=True),
    sa.Column('rfq_no', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfqs_is_archived'), 'rfqs', ['is_archived'], unique=False)
    op.create_index(op.f('ix_rfqs_status'), 'rfqs', ['status'], unique=False)
    op.create_index(op.f('ix_rfqs_tenant_id'), 'rfqs', ['tenant_id'], unique=False)
    op.create_table('tender_bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('bid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('technical_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_bids_is_archived'), 'tender_bids', ['is_archived'], unique=False)
    op.create_index(op.f('ix_tender_bids_tenant_id'), 'tender_bids', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tender_bids_tender_id'), 'tender_bids', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_bids_tender_id'), table_name='tender_bids')
    op.drop_index(op.f('ix_tender_bids_tenant_id'), table_name='tender_bids')
    op.drop_index(op.f('ix_tender_bids_is_archived'), table_name='tender_bids')
    op.drop_table('tender_bids')
    op.drop_index(op.f('ix_rfqs_tenant_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_status'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_is_archived'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index(op.f('ix_payment_certificates_tenant_id'), table_name='payment_certificates')
    op.drop_index(op.f('ix_payment_certificates_status'), table_name='payment_certificates')
    op.drop_index(op.f('ix_payment_certificates_is_archived'), table_name='payment_certificates')
    op.drop_table('payment_certificates')
    op.drop_index(op.f('ix_boq_items_tender_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_tenant_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_is_archived'), table_name='boq_items')
    op.drop_table('boq_items')
    op.drop_index(op.f('ix_tenders_title'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_tenant_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_is_archived'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_submittals_tenant_id'), table_name='submittals')
    op.drop_index(op.f('ix_submittals_status'), table_name='submittals')
    op.drop_index(op.f('ix_submittals_is_archived'), table_name='submittals')
    op.drop_table('submittals')
    op.drop_index(op.f('ix_site_diaries_tenant_id'), table_name='site_diaries')
    op.drop_index(op.f('ix_site_diaries_is_archived'), table_name='site_diaries')
    op.drop_index(op.f('ix_site_diaries_diary_date'), table_name='site_diaries')
    op.drop_table('site_diaries')
    op.drop_index(op.f('ix_purchase_requests_tenant_id'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_status'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_is_archived'), table_name='purchase_requests')
    op.drop_table('purchase_requests')
    op.drop_index(op.f('ix_progress_claims_tenant_id'), table_name='progress_claims')
    op.drop_index(op.f('ix_progress_claims_status'), table_name='progress_claims')
    op.drop_index(op.f('ix_progress_claims_is_archived'), table_name='progress_claims')
    op.drop_table('progress_claims')
    op.drop_index(op.f('ix_inspections_tenant_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_result'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_is_archived'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_goods_receipts_tenant_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_status'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_is_archived'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_e_invoices_tenant_id'), table_name='e_invoices')
    op.drop_index(op.f('ix_e_invoices_status'), table_name='e_invoices')
    op.drop_index(op.f('ix_e_invoices_is_archived'), table_name='e_invoices')
    op.drop_index(op.f('ix_e_invoices_invoice_no'), table_name='e_invoices')
    op.drop_table('e_invoices')
    op.drop_index(op.f('ix_defects_tenant_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_status'), table_name='defects')
    op.drop_index(op.f('ix_defects_severity'), table_name='defects')
    op.drop_index(op.f('ix_defects_is_archived'), table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_vendors_tenant_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_status'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_is_archived'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_cost_codes_tenant_id'), table_name='cost_codes')
    op.drop_index(op.f('ix_cost_codes_is_archived'), table_name='cost_codes')
    op.drop_index(op.f('ix_cost_codes_code'), table_name='cost_codes')
    op.drop_table('cost_codes')
    op.drop_index(op.f('ix_consultants_tenant_id'), table_name='consultants')
    op.drop_index(op.f('ix_consultants_status'), table_name='consultants')
    op.drop_index(op.f('ix_consultants_name'), table_name='consultants')
    op.drop_index(op.f('ix_consultants_is_archived'), table_name='consultants')
    op.drop_table('consultants')
    # ### end Alembic commands ###
