"""add modules 2-7, chat, ocr

Revision ID: 758b615dcf53
Revises: 15f256465248
Create Date: 2026-07-15 07:21:53.427822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758b615dcf53'
down_revision: Union[str, Sequence[str], None] = '15f256465248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_reminders_entity_id'), 'email_reminders', ['entity_id'], unique=False)
    op.create_index(op.f('ix_email_reminders_is_archived'), 'email_reminders', ['is_archived'], unique=False)
    op.create_index(op.f('ix_email_reminders_reminder_date'), 'email_reminders', ['reminder_date'], unique=False)
    op.create_index(op.f('ix_email_reminders_status'), 'email_reminders', ['status'], unique=False)
    op.create_index(op.f('ix_email_reminders_tenant_id'), 'email_reminders', ['tenant_id'], unique=False)
    op.create_table('rate_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('standard_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('lowest_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('highest_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('average_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_items_description'), 'rate_items', ['description'], unique=False)
    op.create_index(op.f('ix_rate_items_is_archived'), 'rate_items', ['is_archived'], unique=False)
    op.create_index(op.f('ix_rate_items_tenant_id'), 'rate_items', ['tenant_id'], unique=False)
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_templates_is_archived'), 'report_templates', ['is_archived'], unique=False)
    op.create_index(op.f('ix_report_templates_name'), 'report_templates', ['name'], unique=False)
    op.create_index(op.f('ix_report_templates_tenant_id'), 'report_templates', ['tenant_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_is_archived'), 'chat_sessions', ['is_archived'], unique=False)
    op.create_index(op.f('ix_chat_sessions_tenant_id'), 'chat_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('cost_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('benchmark_type', sa.String(length=30), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_benchmarks_category'), 'cost_benchmarks', ['category'], unique=False)
    op.create_index(op.f('ix_cost_benchmarks_is_archived'), 'cost_benchmarks', ['is_archived'], unique=False)
    op.create_index(op.f('ix_cost_benchmarks_tenant_id'), 'cost_benchmarks', ['tenant_id'], unique=False)
    op.create_table('final_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('account_no', sa.String(length=60), nullable=False),
    sa.Column('original_contract_sum', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('variation_orders_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approved_claims_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('retention_released', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_accounts_is_archived'), 'final_accounts', ['is_archived'], unique=False)
    op.create_index(op.f('ix_final_accounts_status'), 'final_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_final_accounts_tenant_id'), 'final_accounts', ['tenant_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('reverse_auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('reserve_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('decrement_step', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('leading_vendor_id', sa.Integer(), nullable=True),
    sa.Column('leading_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['leading_vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reverse_auctions_is_archived'), 'reverse_auctions', ['is_archived'], unique=False)
    op.create_index(op.f('ix_reverse_auctions_status'), 'reverse_auctions', ['status'], unique=False)
    op.create_index(op.f('ix_reverse_auctions_tenant_id'), 'reverse_auctions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reverse_auctions_tender_id'), 'reverse_auctions', ['tender_id'], unique=False)
    op.create_table('tender_addenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('addendum_no', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_addenda_is_archived'), 'tender_addenda', ['is_archived'], unique=False)
    op.create_index(op.f('ix_tender_addenda_tenant_id'), 'tender_addenda', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tender_addenda_tender_id'), 'tender_addenda', ['tender_id'], unique=False)
    op.create_table('auction_bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('bid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_leading', sa.Boolean(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['reverse_auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_bids_auction_id'), 'auction_bids', ['auction_id'], unique=False)
    op.create_index(op.f('ix_auction_bids_tenant_id'), 'auction_bids', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auction_bids_tenant_id'), table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_auction_id'), table_name='auction_bids')
    op.drop_table('auction_bids')
    op.drop_index(op.f('ix_tender_addenda_tender_id'), table_name='tender_addenda')
    op.drop_index(op.f('ix_tender_addenda_tenant_id'), table_name='tender_addenda')
    op.drop_index(op.f('ix_tender_addenda_is_archived'), table_name='tender_addenda')
    op.drop_table('tender_addenda')
    op.drop_index(op.f('ix_reverse_auctions_tender_id'), table_name='reverse_auctions')
    op.drop_index(op.f('ix_reverse_auctions_tenant_id'), table_name='reverse_auctions')
    op.drop_index(op.f('ix_reverse_auctions_status'), table_name='reverse_auctions')
    op.drop_index(op.f('ix_reverse_auctions_is_archived'), table_name='reverse_auctions')
    op.drop_table('reverse_auctions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_final_accounts_tenant_id'), table_name='final_accounts')
    op.drop_index(op.f('ix_final_accounts_status'), table_name='final_accounts')
    op.drop_index(op.f('ix_final_accounts_is_archived'), table_name='final_accounts')
    op.drop_table('final_accounts')
    op.drop_index(op.f('ix_cost_benchmarks_tenant_id'), table_name='cost_benchmarks')
    op.drop_index(op.f('ix_cost_benchmarks_is_archived'), table_name='cost_benchmarks')
    op.drop_index(op.f('ix_cost_benchmarks_category'), table_name='cost_benchmarks')
    op.drop_table('cost_benchmarks')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_tenant_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_is_archived'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_report_templates_tenant_id'), table_name='report_templates')
    op.drop_index(op.f('ix_report_templates_name'), table_name='report_templates')
    op.drop_index(op.f('ix_report_templates_is_archived'), table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_rate_items_tenant_id'), table_name='rate_items')
    op.drop_index(op.f('ix_rate_items_is_archived'), table_name='rate_items')
    op.drop_index(op.f('ix_rate_items_description'), table_name='rate_items')
    op.drop_table('rate_items')
    op.drop_index(op.f('ix_email_reminders_tenant_id'), table_name='email_reminders')
    op.drop_index(op.f('ix_email_reminders_status'), table_name='email_reminders')
    op.drop_index(op.f('ix_email_reminders_reminder_date'), table_name='email_reminders')
    op.drop_index(op.f('ix_email_reminders_is_archived'), table_name='email_reminders')
    op.drop_index(op.f('ix_email_reminders_entity_id'), table_name='email_reminders')
    op.drop_table('email_reminders')
    # ### end Alembic commands ###
